---
title: "To do list"
author: "P. M. Evans"
date: "`r format(Sys.time(), '%d/%m/%y')`"
output: html_document
bibliography: E:/CEH/Literature/library.bib
urlcolor: purple
header-includes:
  - \usepackage{placeins}
fig_caption: yes
link-citations: yes
---

\clearpage
\tableofcontents
\clearpage

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)

library(knitr)
```

# Work
## BESTMAP
### General assembly
- Create slides stating work done so far

### Crop yield
- Emailed Luca and John about crop yield - waiting to hear back

## AgLand
### Carbon tool
- Talk to Richard about C contacts (JMB suggested: Chris Evans/ CSS/ Pete Henrys (aboveground C stocks)/ Pete Levy/ Pete Smith/ Richard Pywell)
- create a document about the possible ES, and then circulate - include validation data
- Keep checking for Nathan Fox publications for recreation/ tourism methods
- Quiz for 16th November

## Admin
### RA time
- Check out SDM courses
- Get InVEST Python working on work laptop
- Finish research interests on prolife
- Update LinkedIn


# Personal
## Routine

## Cards

## Life stuff

## Non-CEH Work
- Contact Ainara re QBETER
- Contact Mark re Novgorod
